# Generated by Django 3.1.6 on 2021-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('fill_type', models.CharField(choices=[('CLR', 'COLOR'), ('GRD', 'GRADIENT')], default='CLR', max_length=10)),
                ('color', models.CharField(blank=True, help_text='LIKE AA0192', max_length=6)),
                ('color1', models.CharField(blank=True, help_text='LIKE A90BCA', max_length=6)),
                ('color2', models.CharField(blank=True, help_text='LIKE FED562', max_length=6)),
                ('angle', models.IntegerField(blank=True)),
            ],
        ),
    ]
