# Generated by Django 3.1.6 on 2021-03-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='angle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
